### ISSUE TITLE
Calendario Live

### ISSUE THREAD

**Issue by ftruono** [ftruono/EMAD2020_mygym#10]
Implementare la finestra del calendario eventi

Scrivere il componente in modo che sia predisposto per la visualizzazione e la modifica

|Given| Dato un utente standard o un PT
|When| Che clicca sulle live
|Then| Mostrerà un calendario con gli eventi

|Given| Dato un utente standard sulla finestra delle live
|When| L'utente selziona il giorno dal calendario
|Then| Mostrerà i dettagli della live nella parte sottostante o mediante popup

|Given| Dato un PT che seleziona le live
|When| Il PT seleziona il giorno del calendario
|Then| Mostrerà i dettagli della live, in maniera uniforme con le modalità scelte per l'utente, con l'unica differenza che il campo sarà editabile

**Comment by enzoLiguo** [comment]
Da gestire chiusura modale e gestione Utente semplice

**Comment by ftruono** [comment]
@enzoLiguo La modale su android non si apre come "modale" ma come screen normale, inoltre rimane bloccata in quella pagina.
