### ISSUE TITLE
Dati Personali Utenti

### ISSUE THREAD

**Issue by ftruono** [ftruono/EMAD2020_mygym#13]
Creare la scheramata dei dati personali degli utenti.

**Valutare se si possono creari componenti riutilizzabili**

**Comment by enzoLiguo** [comment]
Da capire tutti insieme come gestire la card di set Palestra: 
Opzione 1: Apertura pop up e nella card solo visualizzazione
Opzione 2: aggiunta dinamica di parti del corpo con dropdown all'interno della card

**Comment by enzoLiguo** [comment]
Scelta Opzione 1
