### ISSUE TITLE
Visualizzazione singolo giorno

### ISSUE THREAD

**Issue by ftruono** [ftruono/EMAD2020_mygym#15]
Implementare la visualizzazione della singola scheda. 

Predisporre il componente che accetta i:

-Elenco allenamenti
-Ripetizioni ( N *)
-Pausa

Predisporre anche i parametri per la finestra successiva

**Comment by enzoLiguo** [comment]
Issue completa si devono solo decidere le sorti del bottone di modifica

**Comment by enzoLiguo** [comment]
Mettere icona modifica vicino a day1 @nellop97
