### ISSUE TITLE
Authentication Flow

### ISSUE THREAD

**Issue by ftruono** [ftruono/EMAD2020_mygym#20]
Implementazione dell'autenticazione dell'utente con firebase.

-Prevedere il contesto di autenticazione di react (flow di documentazione)
-Implementare Login/Logout e Registrazione

Valutare l'uso di firebase autentication oltre firestore

**Comment by ftruono** [comment]
Dopo, la prima parte di implementazione dello stack di autenticazione è necessario riadattare (come già era prevedibile) tutte le finestre con firestore.
Quindi priorità all'integrazione di quello che già c'è 

N.b per motivi di "funzionamento" il file GlobalConfig è rimasto, per cambiare tipo di utente in production per le vostre issue in sospeso, modificate in App.js global.userType

@nellop97 @enzoLiguo.

**Comment by enzoLiguo** [comment]
Feature conclusa
