### ISSUE TITLE
Homepage User

### ISSUE THREAD

**Issue by ftruono** [ftruono/EMAD2020_mygym#9]
Creare la schermata del utente

- Prevedere il caso in cui abbia già dati (Supporre che ci siano dei dati)
- Prevedere il caso in cui non abbia dei dati

Ragionare anche su un eventuale messa a comune di un componente homepage

Gerarchia componenti:
- Homepage (Astratta)
  - Homepage User
  - Homepage PT
  - Homepage Nutrizionista

**IMPORTANTE RIUTILIZZARE IL CODICE**

**Comment by enzoLiguo** [comment]
Lato backend la home user è conclusa aperta altra issue per gli altri tipi di utenti NT e PT
